#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v16
# autospec commit: b858a2a
#
Name     : snapshot
Version  : 46.3
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/snapshot/-/archive/46.3/snapshot-46.3.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/snapshot/-/archive/46.3/snapshot-46.3.tar.gz
Source1  : http://localhost/cgit/vendor/snapshot/snapshot/snapshot-2024-07-15-23-03-29.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0 ICU MIT MPL-2.0-no-copyleft-exception Unicode-DFS-2016 Unlicense
Requires: snapshot-bin = %{version}-%{release}
Requires: snapshot-data = %{version}-%{release}
Requires: snapshot-license = %{version}-%{release}
Requires: snapshot-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gstreamer-dev
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-bad-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!-- <a href="https://flathub.org/apps/details/org.gnome.Snapshot"> -->
<!-- <img src="https://flathub.org/assets/badges/flathub-badge-i-en.png" width="190px" /> -->
<!-- </a> -->

%package bin
Summary: bin components for the snapshot package.
Group: Binaries
Requires: snapshot-data = %{version}-%{release}
Requires: snapshot-license = %{version}-%{release}

%description bin
bin components for the snapshot package.


%package data
Summary: data components for the snapshot package.
Group: Data

%description data
data components for the snapshot package.


%package license
Summary: license components for the snapshot package.
Group: Default

%description license
license components for the snapshot package.


%package locales
Summary: locales components for the snapshot package.
Group: Default

%description locales
locales components for the snapshot package.


%prep
%setup -q -n snapshot-46.3
cd %{_builddir}
tar xf %{_sourcedir}/snapshot-2024-07-15-23-03-29.tar.xz
cd %{_builddir}/snapshot-46.3
mkdir -p ./vendor
cp -r %{_builddir}/snapshot-2024-07-15-23-03-29/* %{_builddir}/snapshot-46.3/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721085744
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/snapshot
cp %{_builddir}/snapshot-2024-07-15-23-03-29/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/snapshot/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/snapshot/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/android-tzdata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/db8bf4070b91bbabe0f14d1c15f0be86793fab6a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/android-tzdata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/2c87153926f8a458cffc9a435e15571ba721c2fa || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/android_system_properties/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/android_system_properties/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ac0bf7546a377351144d930c5e31eff058fe4e8f || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/async-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/async-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/atomic_refcell/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/snapshot/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/bumpalo/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/bumpalo/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/0a1e89ac22450cb0311baa2613bc21b7131b321f || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cairo-rs/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cairo-rs/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cairo-sys-rs/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cfg-expr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cfg-expr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/0dce8bdb8d707f18cd507fddb418b397a84f886a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/chrono/LICENSE.txt %{buildroot}/usr/share/package-licenses/snapshot/c145b1a607ecf06aed81f1d04a65c2e43dffdc63 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/concurrent-queue/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/concurrent-queue/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/core-foundation-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/core-foundation-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/event-listener-strategy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/event-listener-strategy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/event-listener/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/event-listener/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/field-offset/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/field-offset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/35285d4b7e96ddc000f3a3d3e7634542b407ee63 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-executor/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-executor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-io/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-io/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-task/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-task/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-util/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/futures-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk-pixbuf-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk-pixbuf/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk-pixbuf/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-wayland-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-wayland/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-wayland/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-win32-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-win32/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-win32/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-x11-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-x11/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4-x11/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gdk4/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gettext-rs/LICENSE.txt %{buildroot}/usr/share/package-licenses/snapshot/9d2cd46d137bf85f114915560f5c50fdf2612f02 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gettext-sys/LICENSE.txt %{buildroot}/usr/share/package-licenses/snapshot/9d2cd46d137bf85f114915560f5c50fdf2612f02 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gio-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gio/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gio/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/glib-macros/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/glib-macros/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/glib-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/glib/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/glib/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gobject-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/graphene-rs/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/graphene-rs/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/graphene-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gsk4-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gsk4/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gsk4/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gst-plugin-gtk4/LICENSE-MPL-2.0 %{buildroot}/usr/share/package-licenses/snapshot/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gst-plugin-version-helper/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-audio-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-audio/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-audio/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-base-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-base/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-base/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-egl-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-egl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-egl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-wayland-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-wayland/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-wayland/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-x11-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-x11/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl-x11/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-gl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-pbutils-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-pbutils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-pbutils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-video-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-video/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer-video/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gstreamer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gtk4-macros/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gtk4-macros/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gtk4-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gtk4/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/gtk4/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/iana-time-zone-haiku/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/iana-time-zone-haiku/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/iana-time-zone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/iana-time-zone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/js-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/js-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/libadwaita-sys/LICENCE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/libadwaita/LICENCE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/locale_config/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/2e040ff5e44fbd2796ade7bce886a226ea10f651 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/memchr/COPYING %{buildroot}/usr/share/package-licenses/snapshot/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/snapshot/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/muldiv/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/f37668e1c05e3b40d5035518130e0ce60f435719 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/nu-ansi-term/LICENCE %{buildroot}/usr/share/package-licenses/snapshot/fea05fa01bac661c706e9e134d9d80b2248bb065 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-rational/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-rational/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/objc/LICENSE.txt %{buildroot}/usr/share/package-licenses/snapshot/b6701831988d077f53d90abce09a2887fc7b5ea9 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/option-operations/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/option-operations/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/overload/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/839963b8e6356d7d297f5124373d62b4c88ac3a8 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pango-sys/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pango/COPYRIGHT %{buildroot}/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pango/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/parking/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/parking/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/paste/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/paste/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pin-project-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pin-project-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pin-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/a2f60339450a52e61c6c1e27dc44bd1e671ad28e || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pin-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/91abce61ea0c1c313bb5ba31f04196490960a479 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-crate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-crate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-error-attr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/a88eaffea57a51eedb5291e0d55a959df7659458 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-error-attr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/197cb40dc96ded1e036d13ef67fdc7a758ca1388 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro-error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/655a437377cc2780990746fe2492fa16764df083 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/snapshot/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/rustc_version/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/rustc_version/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/semver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/semver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde_spanned/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/serde_spanned/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/sharded-slab/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/f591e1908efe604899b6cdcf5716e96665852778 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/slab/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/96f019e8abadc7a87b330a697504d874a1c06268 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/system-deps/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/system-deps/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thread_local/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/thread_local/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_datetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_datetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_edit-0.21.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_edit-0.21.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_edit/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/toml_edit/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/tracing-core/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/tracing-core/src/spin/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/0956f8ac49e23a546fb113f711d7cdc0c3e98c85 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/tracing-log/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/tracing-subscriber/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/snapshot/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/version-compare/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/bbca91a10afe6e9d066acdd53930d0c47eb08803 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-macro-support/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-macro-support/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-shared/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen-shared/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/wasm-bindgen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/snapshot/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-core/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-core/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/winnow-0.5.40/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca || :
cp %{_builddir}/snapshot-2024-07-15-23-03-29/winnow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/snapshot/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca || :
cp %{_builddir}/snapshot-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/07ff10644d21f27d4a9d04f37b91e13b751edc7e || :
cp %{_builddir}/snapshot-%{version}/aperture/LICENSE %{buildroot}/usr/share/package-licenses/snapshot/c1e0b729040562ad35640ef22844ab8024f9e340 || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang snapshot

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/snapshot

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Snapshot.desktop
/usr/share/glib-2.0/schemas/org.gnome.Snapshot.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Snapshot.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Snapshot-symbolic.svg
/usr/share/metainfo/org.gnome.Snapshot.metainfo.xml
/usr/share/snapshot/resources.gresource

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/snapshot/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/snapshot/067f31555f328efb78075174add7db97d98618c6
/usr/share/package-licenses/snapshot/07ff10644d21f27d4a9d04f37b91e13b751edc7e
/usr/share/package-licenses/snapshot/0956f8ac49e23a546fb113f711d7cdc0c3e98c85
/usr/share/package-licenses/snapshot/0a1e89ac22450cb0311baa2613bc21b7131b321f
/usr/share/package-licenses/snapshot/0dce8bdb8d707f18cd507fddb418b397a84f886a
/usr/share/package-licenses/snapshot/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/snapshot/197cb40dc96ded1e036d13ef67fdc7a758ca1388
/usr/share/package-licenses/snapshot/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/snapshot/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/snapshot/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/snapshot/2c87153926f8a458cffc9a435e15571ba721c2fa
/usr/share/package-licenses/snapshot/2e040ff5e44fbd2796ade7bce886a226ea10f651
/usr/share/package-licenses/snapshot/35285d4b7e96ddc000f3a3d3e7634542b407ee63
/usr/share/package-licenses/snapshot/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/snapshot/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/snapshot/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/snapshot/3c8e7847ca19c2bb00f4100c725810c04a1b56d6
/usr/share/package-licenses/snapshot/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/snapshot/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/snapshot/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/snapshot/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/snapshot/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/snapshot/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/snapshot/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/snapshot/655a437377cc2780990746fe2492fa16764df083
/usr/share/package-licenses/snapshot/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/snapshot/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/snapshot/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/snapshot/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/snapshot/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/snapshot/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/snapshot/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/snapshot/839963b8e6356d7d297f5124373d62b4c88ac3a8
/usr/share/package-licenses/snapshot/91abce61ea0c1c313bb5ba31f04196490960a479
/usr/share/package-licenses/snapshot/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/snapshot/954d187b36fac82f7bb46a25b7d21b1fca75be97
/usr/share/package-licenses/snapshot/96f019e8abadc7a87b330a697504d874a1c06268
/usr/share/package-licenses/snapshot/9744cedce099f727b327cd9913a1fdc58a7f5599
/usr/share/package-licenses/snapshot/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/snapshot/9d2cd46d137bf85f114915560f5c50fdf2612f02
/usr/share/package-licenses/snapshot/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/snapshot/a2f60339450a52e61c6c1e27dc44bd1e671ad28e
/usr/share/package-licenses/snapshot/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/snapshot/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
/usr/share/package-licenses/snapshot/a88eaffea57a51eedb5291e0d55a959df7659458
/usr/share/package-licenses/snapshot/a8ab3e6caa5e7af0ec9235d5db800ace830c0a38
/usr/share/package-licenses/snapshot/ac0bf7546a377351144d930c5e31eff058fe4e8f
/usr/share/package-licenses/snapshot/b6701831988d077f53d90abce09a2887fc7b5ea9
/usr/share/package-licenses/snapshot/bbca91a10afe6e9d066acdd53930d0c47eb08803
/usr/share/package-licenses/snapshot/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca
/usr/share/package-licenses/snapshot/c145b1a607ecf06aed81f1d04a65c2e43dffdc63
/usr/share/package-licenses/snapshot/c1e0b729040562ad35640ef22844ab8024f9e340
/usr/share/package-licenses/snapshot/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/snapshot/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/snapshot/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/snapshot/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/snapshot/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/snapshot/d3f4001d9de83a122956c9195d73e2507bf6c533
/usr/share/package-licenses/snapshot/d552e9ea99ac411f45bda877729a38461a13248b
/usr/share/package-licenses/snapshot/db8bf4070b91bbabe0f14d1c15f0be86793fab6a
/usr/share/package-licenses/snapshot/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/snapshot/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/snapshot/e81567c196622efa36b46c5fd53cde741aaf0993
/usr/share/package-licenses/snapshot/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/snapshot/f37668e1c05e3b40d5035518130e0ce60f435719
/usr/share/package-licenses/snapshot/f591e1908efe604899b6cdcf5716e96665852778
/usr/share/package-licenses/snapshot/fea05fa01bac661c706e9e134d9d80b2248bb065
/usr/share/package-licenses/snapshot/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/snapshot/ff44b187892fcf1cd15a3ca61b498041b28afecc

%files locales -f snapshot.lang
%defattr(-,root,root,-)

